# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class McpServerName(str, enum.Enum):
    MARKDOWN2DOC = "Markdown2doc"
    SLACK = "Slack"
    SUPABASE = "Supabase"
    POSTGRES = "Postgres"
    YOU_TUBE = "YouTube"
    DOC2MARKDOWN = "Doc2markdown"
    KLAVIS_REPORT_GEN = "Klavis ReportGen"
    RESEND = "Resend"
    DISCORD = "Discord"
    FIRECRAWL_WEB_SEARCH = "Firecrawl Web Search"
    GIT_HUB = "GitHub"
    FIRECRAWL_DEEP_RESEARCH = "Firecrawl Deep Research"
    JIRA = "Jira"
    CONFLUENCE = "Confluence"
    WORD_PRESS = "WordPress"
    NOTION = "Notion"
    GMAIL = "Gmail"
    GOOGLE_DRIVE = "Google Drive"
    GOOGLE_CALENDAR = "Google Calendar"
    GOOGLE_SHEETS = "Google Sheets"
    GOOGLE_DOCS = "Google Docs"
    ATTIO = "Attio"
    SALESFORCE = "Salesforce"
    LINEAR = "Linear"
    ASANA = "Asana"
    CLOSE = "Close"
    GONG = "Gong"
    CLICK_UP = "ClickUp"

    def visit(
        self,
        markdown2doc: typing.Callable[[], T_Result],
        slack: typing.Callable[[], T_Result],
        supabase: typing.Callable[[], T_Result],
        postgres: typing.Callable[[], T_Result],
        you_tube: typing.Callable[[], T_Result],
        doc2markdown: typing.Callable[[], T_Result],
        klavis_report_gen: typing.Callable[[], T_Result],
        resend: typing.Callable[[], T_Result],
        discord: typing.Callable[[], T_Result],
        firecrawl_web_search: typing.Callable[[], T_Result],
        git_hub: typing.Callable[[], T_Result],
        firecrawl_deep_research: typing.Callable[[], T_Result],
        jira: typing.Callable[[], T_Result],
        confluence: typing.Callable[[], T_Result],
        word_press: typing.Callable[[], T_Result],
        notion: typing.Callable[[], T_Result],
        gmail: typing.Callable[[], T_Result],
        google_drive: typing.Callable[[], T_Result],
        google_calendar: typing.Callable[[], T_Result],
        google_sheets: typing.Callable[[], T_Result],
        google_docs: typing.Callable[[], T_Result],
        attio: typing.Callable[[], T_Result],
        salesforce: typing.Callable[[], T_Result],
        linear: typing.Callable[[], T_Result],
        asana: typing.Callable[[], T_Result],
        close: typing.Callable[[], T_Result],
        gong: typing.Callable[[], T_Result],
        click_up: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is McpServerName.MARKDOWN2DOC:
            return markdown2doc()
        if self is McpServerName.SLACK:
            return slack()
        if self is McpServerName.SUPABASE:
            return supabase()
        if self is McpServerName.POSTGRES:
            return postgres()
        if self is McpServerName.YOU_TUBE:
            return you_tube()
        if self is McpServerName.DOC2MARKDOWN:
            return doc2markdown()
        if self is McpServerName.KLAVIS_REPORT_GEN:
            return klavis_report_gen()
        if self is McpServerName.RESEND:
            return resend()
        if self is McpServerName.DISCORD:
            return discord()
        if self is McpServerName.FIRECRAWL_WEB_SEARCH:
            return firecrawl_web_search()
        if self is McpServerName.GIT_HUB:
            return git_hub()
        if self is McpServerName.FIRECRAWL_DEEP_RESEARCH:
            return firecrawl_deep_research()
        if self is McpServerName.JIRA:
            return jira()
        if self is McpServerName.CONFLUENCE:
            return confluence()
        if self is McpServerName.WORD_PRESS:
            return word_press()
        if self is McpServerName.NOTION:
            return notion()
        if self is McpServerName.GMAIL:
            return gmail()
        if self is McpServerName.GOOGLE_DRIVE:
            return google_drive()
        if self is McpServerName.GOOGLE_CALENDAR:
            return google_calendar()
        if self is McpServerName.GOOGLE_SHEETS:
            return google_sheets()
        if self is McpServerName.GOOGLE_DOCS:
            return google_docs()
        if self is McpServerName.ATTIO:
            return attio()
        if self is McpServerName.SALESFORCE:
            return salesforce()
        if self is McpServerName.LINEAR:
            return linear()
        if self is McpServerName.ASANA:
            return asana()
        if self is McpServerName.CLOSE:
            return close()
        if self is McpServerName.GONG:
            return gong()
        if self is McpServerName.CLICK_UP:
            return click_up()
