# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.confluence_o_auth_success_response import ConfluenceOAuthSuccessResponse
from .raw_client import AsyncRawConfluenceOauthClient, RawConfluenceOauthClient


class ConfluenceOauthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConfluenceOauthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConfluenceOauthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConfluenceOauthClient
        """
        return self._raw_client

    def authorize_confluence(
        self,
        *,
        instance_id: str,
        client_id: typing.Optional[str] = None,
        scope: typing.Optional[str] = None,
        redirect_url: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Start Confluence OAuth flow

        Parameters:
        - instance_id: Identifier for the instance requesting authorization
        - client_id: Optional client ID for white labeling
        - scope: Optional scopes to request (comma-separated)
        - redirect_url: Optional URL to redirect to after authorization completes

        Parameters
        ----------
        instance_id : str
            Unique identifier for the client instance requesting authorization

        client_id : typing.Optional[str]
            Client ID for white labeling, if not provided will use default credentials

        scope : typing.Optional[str]
            Optional OAuth scopes to request (comma-separated string)

        redirect_url : typing.Optional[str]
            Optional URL to redirect to after authorization completes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from klavis import Klavis

        client = Klavis(
            token="YOUR_TOKEN",
        )
        client.confluence_oauth.authorize_confluence(
            instance_id="instance_id",
        )
        """
        _response = self._raw_client.authorize_confluence(
            instance_id=instance_id,
            client_id=client_id,
            scope=scope,
            redirect_url=redirect_url,
            request_options=request_options,
        )
        return _response.data

    def confluence_o_auth_callback(
        self,
        *,
        code: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        error: typing.Optional[str] = None,
        error_description: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConfluenceOAuthSuccessResponse:
        """
        Handles the callback from Confluence OAuth authorization.

        Parameters
        ----------
        code : typing.Optional[str]
            Authorization code returned by Confluence

        state : typing.Optional[str]
            State parameter containing encoded authorization data

        error : typing.Optional[str]
            Error code returned by Confluence, if any

        error_description : typing.Optional[str]
            Detailed error description from Confluence, if any

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfluenceOAuthSuccessResponse
            Successful Response

        Examples
        --------
        from klavis import Klavis

        client = Klavis(
            token="YOUR_TOKEN",
        )
        client.confluence_oauth.confluence_o_auth_callback()
        """
        _response = self._raw_client.confluence_o_auth_callback(
            code=code, state=state, error=error, error_description=error_description, request_options=request_options
        )
        return _response.data

    def refresh_confluence_token(
        self, *, instance_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ConfluenceOAuthSuccessResponse:
        """
        Refresh an expired Confluence access token using the stored refresh token

        Parameters:
        - instance_id: Identifier for the instance requesting token refresh

        Returns:
        - Success response if token was refreshed successfully, error response otherwise

        Parameters
        ----------
        instance_id : str
            Unique identifier for the client instance requesting token refresh

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfluenceOAuthSuccessResponse
            Successful Response

        Examples
        --------
        from klavis import Klavis

        client = Klavis(
            token="YOUR_TOKEN",
        )
        client.confluence_oauth.refresh_confluence_token(
            instance_id="instance_id",
        )
        """
        _response = self._raw_client.refresh_confluence_token(instance_id=instance_id, request_options=request_options)
        return _response.data


class AsyncConfluenceOauthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConfluenceOauthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConfluenceOauthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConfluenceOauthClient
        """
        return self._raw_client

    async def authorize_confluence(
        self,
        *,
        instance_id: str,
        client_id: typing.Optional[str] = None,
        scope: typing.Optional[str] = None,
        redirect_url: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Start Confluence OAuth flow

        Parameters:
        - instance_id: Identifier for the instance requesting authorization
        - client_id: Optional client ID for white labeling
        - scope: Optional scopes to request (comma-separated)
        - redirect_url: Optional URL to redirect to after authorization completes

        Parameters
        ----------
        instance_id : str
            Unique identifier for the client instance requesting authorization

        client_id : typing.Optional[str]
            Client ID for white labeling, if not provided will use default credentials

        scope : typing.Optional[str]
            Optional OAuth scopes to request (comma-separated string)

        redirect_url : typing.Optional[str]
            Optional URL to redirect to after authorization completes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from klavis import AsyncKlavis

        client = AsyncKlavis(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.confluence_oauth.authorize_confluence(
                instance_id="instance_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.authorize_confluence(
            instance_id=instance_id,
            client_id=client_id,
            scope=scope,
            redirect_url=redirect_url,
            request_options=request_options,
        )
        return _response.data

    async def confluence_o_auth_callback(
        self,
        *,
        code: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        error: typing.Optional[str] = None,
        error_description: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConfluenceOAuthSuccessResponse:
        """
        Handles the callback from Confluence OAuth authorization.

        Parameters
        ----------
        code : typing.Optional[str]
            Authorization code returned by Confluence

        state : typing.Optional[str]
            State parameter containing encoded authorization data

        error : typing.Optional[str]
            Error code returned by Confluence, if any

        error_description : typing.Optional[str]
            Detailed error description from Confluence, if any

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfluenceOAuthSuccessResponse
            Successful Response

        Examples
        --------
        import asyncio

        from klavis import AsyncKlavis

        client = AsyncKlavis(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.confluence_oauth.confluence_o_auth_callback()


        asyncio.run(main())
        """
        _response = await self._raw_client.confluence_o_auth_callback(
            code=code, state=state, error=error, error_description=error_description, request_options=request_options
        )
        return _response.data

    async def refresh_confluence_token(
        self, *, instance_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ConfluenceOAuthSuccessResponse:
        """
        Refresh an expired Confluence access token using the stored refresh token

        Parameters:
        - instance_id: Identifier for the instance requesting token refresh

        Returns:
        - Success response if token was refreshed successfully, error response otherwise

        Parameters
        ----------
        instance_id : str
            Unique identifier for the client instance requesting token refresh

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfluenceOAuthSuccessResponse
            Successful Response

        Examples
        --------
        import asyncio

        from klavis import AsyncKlavis

        client = AsyncKlavis(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.confluence_oauth.refresh_confluence_token(
                instance_id="instance_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refresh_confluence_token(
            instance_id=instance_id, request_options=request_options
        )
        return _response.data
